jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            default:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/config/serializer"
