App\Model\AbstractEntry:
  exclusion_policy: ALL
  properties:
    temperature:
      type: float
      expose: true
    cloudiness:
      type: float
      expose: true
    windSpeed:
      type: float
      expose: true
      serialized_name: windSpeed
    description:
      type: string
      expose: true
    requestTime:
      type: int
      expose: true
      serialized_name: requestTime
