App\Model\Response\EntryPage:
  exclusion_policy: ALL
  properties:
    items:
      type: array<App\Model\Response\Entry>
      expose: true
    total:
      type: integer
      expose: true
    pageSize:
      type: integer
      expose: true
      serialized_name: pageSize
